### ISSUE TITLE
0net.io is DOWN

### ISSUE THREAD

**Issue by gjhklfdsa** [AceLewis/AceZeroProxy#10]
**Issue**: 0net.io website is down.
Proof: https://archive.fo/YI0h2, https://web.archive.org/web20190502021258/http://downforeveryoneorjustme.com/web

This may be my connection so I recommend checking for yourself.

However, if I understand correctly this is the last major Zeronet proxy.
Are any left?

**Comment by gjhklfdsa** [comment]
https://archive.fo/ViibB

**Comment by AceLewis** [comment]
I have removed that proxy from the list.
