### ISSUE TITLE
zeronet.now.im now works

### ISSUE THREAD

**Issue by CrocodileCroco** [AceLewis/AceZeroProxy#15]
zeronet.now.im seems to not display an error anymore, i think it can be re-added to the list

**Comment by AceLewis** [comment]
Thanks, I will wait a bit before re-adding to see if it continues to be stable but if you know any other proxies do tell me.

0net-preview.duckdns.org is stable so it is not a priority to add zeronet.now.im yet.

**Comment by tlaurion** [comment]
@AceLewis bump.
