### ISSUE TITLE
Documentation to run new public proxies

### ISSUE THREAD

**Issue by tlaurion** [AceLewis/AceZeroProxy#17]
@AceLewis said:
>I made a (now dated) video showing how to set up a proxy, if people make public proxies they can be added to the list. 

Where is the documentation/Video? Where people can find how to run public proxies?

**Comment by AceLewis** [comment]
Video by me: https://www.youtube.com/watch?v=9wnPv7Q5UA0

But this is 3 years old and might be dated. However, if you are thinking of running a public proxy then list it here.
